name: LaTeX DD actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: "write"
      pull-requests: "read"
    timeout-minutes: 30
    steps:
      - name: Setup repo 
        uses: actions/checkout@v3
      - name: Compile document
        uses: xu-cheng/latex-action@v3            
        with:
          root_file: main.tex
          working_directory: DDwip
      - name: Upload file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: DDmain.pdf