name: LaTeX RASD actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: "write"
      pull-requests: "read"
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - run: cd RASDwip
      - uses: xu-cheng/latex-action@v3            
        with:
          root_file: main.tex
          working_directory: RASDwip
      - run: cp main.pdf RASD_main.pdf
      - uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: RASD_main.pdf